# SOPS key for secrets
keys:
  - &user_wolframite  age1kef20n2n6cgs4rrv76zwg50q0y8xqzpce69twyrrsct6v63cqplqf297my
  # - &user_joeysaur    age
  - &host_su-ana      age1trtaqq9n93gck0gh4ew3ms6unu9qqd34yekhlla0ldn8mygjw46qnspvz5
creation_rules:
  - path_regex: ^secrets/user/[^/]+\.(yaml|json|key)$
    key_groups:
    - age:
      - *user_wolframite
      # - *user_joeysaur
  - path_regex: ^secrets/user/wolframite/[^/]+\.(yaml|json|key)$
    key_groups:
    - age:
      - *user_wolframite
  # - path_regex: ^secrets/user/joeysaur/[^/]+\.(yaml|json|key)$
  #   key_groups:
  #   - age:
  #     - *user_joeysaur
  - path_regex: ^secrets/host/[^/]+\.(yaml|json|key)$
    key_groups:
    - age:
      - *host_su-ana
      # - *host_yel-ana
  - path_regex: ^secrets/host/su-ana/[^/]+\.(yaml|json|key)$
    key_groups:
    - age:
      - *host_su-ana
  # - path_regex: ^secrets/host/yel-ana/[^/]+\.(yaml|json|key)$
  #   key_groups:
  #   - age:
  #     - *host_yel-ana_
