"""Playlist synchronization for beets-alternatives collections."""

from __future__ import annotations

import os
import unicodedata
from pathlib import Path
from typing import TYPE_CHECKING

import confuse
from beets import config
from beets.ui import UserError

from . import playlist

if TYPE_CHECKING:
    from beets.library import Item, Library
    from beets.plugins import BeetsPlugin


PLAYLIST_SUFFIXES: set[str] = {".m3u", ".m3u8"}
LEGACY_GENERATED_MARKER = "# Generated by beet alternatives"


def sync_updated_collections(
    plugin: BeetsPlugin,
    lib: Library,
    collections: set[str],
) -> None:
    """Synchronize playlists for touched alternatives collections."""
    directories = {}
    for collection in collections:
        directory = _normalized_path(_alternative_directory(lib, collection))
        if directory in directories:
            raise UserError(
                "alternatives collections share a playlist directory: "
                f"{directories[directory]}, {collection}"
            )
        directories[directory] = collection

    for collection in sorted(collections):
        count = sync_collection_playlists(lib, collection)
        plugin._log.info(
            "Synchronized {} playlist(s) for alternatives collection {}",
            count,
            collection,
        )


def sync_all_collections(plugin: BeetsPlugin, lib: Library) -> None:
    """Synchronize every configured alternatives collection."""
    sync_updated_collections(plugin, lib, configured_collections())


def configured_collections() -> set[str]:
    """Return collection names from the beets-alternatives configuration."""
    try:
        configured = config["alternatives"].flatten()
    except confuse.NotFoundError:
        return set()

    return {
        str(name)
        for name, value in configured.items()
        if isinstance(value, dict)
    }


def sync_collection_playlists(lib: Library, collection: str) -> int:
    """Copy and rewrite playlists for one alternatives collection."""
    target_dir = _alternative_directory(lib, collection)
    source_dir = _playlist_dir(lib)
    item_by_path = _items_by_path(lib)

    if not source_dir.exists():
        return 0

    same_directory = target_dir.resolve() == source_dir.resolve()
    if target_dir.exists():
        try:
            same_directory = same_directory or os.path.samefile(target_dir, source_dir)
        except OSError:
            pass

    if same_directory:
        raise UserError(
            f"alternatives directory overlaps playlist directory: {target_dir}"
        )

    source_playlists = _playlist_files(source_dir)
    planned = []
    for source_playlist in source_playlists:
        target_playlist = target_dir / source_playlist.name
        entries = _translated_entries(
            source_playlist,
            _playlist_relative_to(lib, source_playlist),
            target_dir,
            item_by_path,
            collection,
        )
        planned.append((target_playlist, entries))

    synced_count = 0
    for target_playlist, entries in planned:
        marker = _generated_marker(collection)
        if entries:
            _require_marker_or_missing(target_playlist, marker)
            playlist.atomic_write_text(
                target_playlist,
                "\n".join([marker, *entries]) + "\n",
            )
            synced_count += 1
        else:
            _remove_generated_playlist(target_playlist, collection)

    source_names = {_name_key(path.name) for path in source_playlists}
    if target_dir.exists():
        for target_playlist in target_dir.iterdir():
            if (
                target_playlist.suffix.lower() in PLAYLIST_SUFFIXES
                and _name_key(target_playlist.name) not in source_names
            ):
                _remove_generated_playlist(target_playlist, collection)

    return synced_count


def _translated_entries(
    source_playlist: Path,
    relative_to: Path,
    target_dir: Path,
    item_by_path: dict[str, Item],
    collection: str,
) -> list[str]:
    entries = []

    for source_path in _read_playlist_entries(source_playlist, relative_to):
        item = item_by_path.get(_normalized_path(source_path))
        if item is None:
            continue

        target_path = _alternative_item_path(item, collection)
        if (
            target_path is None
            or not target_path.is_file()
            or not _is_relative_to(target_path, target_dir)
        ):
            continue

        entry = os.path.relpath(target_path, target_dir)
        if _forward_slash():
            entry = entry.replace(os.sep, "/")
        entries.append(entry)

    return entries


def _read_playlist_entries(path: Path, relative_to: Path) -> list[Path]:
    entries = []

    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (PermissionError, UnicodeDecodeError, OSError) as exc:
        raise UserError(f"could not read playlist {path}: {exc}") from exc

    for raw_line in lines:
        line = raw_line
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if "://" in line.strip():
            raise UserError(f"URL playlist entries are not supported: {line}")

        entry = Path(line).expanduser()
        if not entry.is_absolute():
            entry = relative_to / entry

        entries.append(entry)

    return entries


def _playlist_files(directory: Path) -> list[Path]:
    if not directory.exists():
        return []

    return sorted(
        path
        for path in directory.iterdir()
        if path.is_file() and path.suffix.lower() in PLAYLIST_SUFFIXES
    )


def _alternative_item_path(item: Item, collection: str) -> Path | None:
    path = item.get(f"alt.{collection}")
    if not path:
        return None

    return Path(os.fsdecode(path))


def _items_by_path(lib: Library) -> dict[str, Item]:
    items = {}
    for item in lib.items():
        path = _normalized_path(_path_from_beets(item.path))
        if path in items:
            raise UserError(f"multiple library items use the same path: {item.path}")
        items[path] = item
    return items


def _alternative_directory(lib: Library, collection: str) -> Path:
    try:
        configured = Path(
            config["alternatives"][collection]["directory"].get(str)
        ).expanduser()
    except confuse.NotFoundError:
        configured = Path(collection)
    if configured.is_absolute():
        return configured

    return _path_from_beets(lib.directory) / configured


def _playlist_dir(lib: Library) -> Path:
    return playlist._playlist_dir(lib)


def _playlist_relative_to(lib: Library, playlist_path: Path | None = None) -> Path:
    return playlist._relative_to(
        lib,
        playlist_path or _playlist_dir(lib),
    )


def _path_from_beets(path) -> Path:
    return Path(os.fsdecode(path))


def _normalized_path(path: Path) -> str:
    normalized = os.path.realpath(os.path.expanduser(os.fspath(path)))
    return unicodedata.normalize("NFC", normalized).casefold()


def _forward_slash() -> bool:
    return playlist._forward_slash()


def _is_relative_to(path: Path, directory: Path) -> bool:
    candidate = os.path.abspath(path)
    root = os.path.abspath(directory)
    candidate = unicodedata.normalize("NFC", candidate).casefold()
    root = unicodedata.normalize("NFC", root).casefold()
    try:
        return os.path.commonpath([candidate, root]) == root
    except ValueError:
        return False


def _remove_generated_playlist(path: Path, collection: str) -> None:
    if path.is_symlink() or not path.is_file():
        return

    try:
        first_line = path.read_text(encoding="utf-8").splitlines()[:1]
    except (PermissionError, UnicodeDecodeError, OSError):
        return

    if first_line in ([LEGACY_GENERATED_MARKER], [_generated_marker(collection)]):
        path.unlink()


def _name_key(name: str) -> str:
    return unicodedata.normalize("NFC", name).casefold()


def _generated_marker(collection: str) -> str:
    return f"# Generated by beet alternatives:{collection}"


def _require_marker_or_missing(path: Path, marker: str) -> None:
    if not path.exists() and not path.is_symlink():
        return
    if path.is_symlink() or not path.is_file():
        raise UserError(f"refusing to overwrite unowned playlist: {path}")

    try:
        first_line = path.read_text(encoding="utf-8").splitlines()[:1]
    except (PermissionError, UnicodeDecodeError, OSError) as exc:
        raise UserError(f"could not verify playlist ownership: {path}: {exc}") from exc

    if first_line not in ([LEGACY_GENERATED_MARKER], [marker]):
        raise UserError(f"refusing to overwrite unowned playlist: {path}")
