"""Synchronize main-library playlists into alternatives collections."""

from __future__ import annotations

import os
import tempfile
import unicodedata
from pathlib import Path
from typing import TYPE_CHECKING

import confuse
from beets import config
from beets.ui import UserError

if TYPE_CHECKING:
    from beets.library import Item, Library
    from beets.plugins import BeetsPlugin

PLAYLIST_SUFFIXES: set[str] = {".m3u", ".m3u8"}
LEGACY_GENERATED_MARKER = "# Generated by beet alternatives"


def sync_collection_playlists(
    plugin: BeetsPlugin,
    lib: Library,
    collection: str,
) -> None:
    """Rewrite every main playlist for one alternatives collection."""
    target_dir = _alternative_directory(lib, collection)
    source_dir = _playlist_dir(lib)
    if not source_dir.exists():
        return
    if _same_directory(source_dir, target_dir):
        raise UserError(
            f"alternatives directory overlaps playlist directory: {target_dir}"
        )

    item_by_path = _items_by_path(lib)
    source_playlists = _playlist_files(source_dir)
    planned = [
        (
            target_dir / source_playlist.name,
            _translated_entries(
                source_playlist,
                _playlist_relative_to(lib, source_playlist),
                target_dir,
                item_by_path,
                collection,
            ),
        )
        for source_playlist in source_playlists
    ]

    marker = _generated_marker(collection)
    synced = 0
    for target_playlist, entries in planned:
        if entries:
            _require_marker_or_missing(target_playlist, marker)
            _atomic_write_text(
                target_playlist,
                "\n".join([marker, *entries]) + "\n",
            )
            synced += 1
        else:
            _remove_generated_playlist(target_playlist, collection)

    source_names = {_name_key(path.name) for path in source_playlists}
    if target_dir.exists():
        for target_playlist in target_dir.iterdir():
            if (
                target_playlist.suffix.lower() in PLAYLIST_SUFFIXES
                and _name_key(target_playlist.name) not in source_names
            ):
                _remove_generated_playlist(target_playlist, collection)

    plugin._log.info(
        "Synchronized {} playlist(s) for alternatives collection {}",
        synced,
        collection,
    )


def _translated_entries(
    source_playlist: Path,
    relative_to: Path,
    target_dir: Path,
    item_by_path: dict[str, Item],
    collection: str,
) -> list[str]:
    entries = []
    for source_path in _read_playlist_entries(source_playlist, relative_to):
        item = item_by_path.get(_normalized_path(source_path))
        if item is None:
            continue

        target_path = _alternative_item_path(item, collection)
        if (
            target_path is None
            or not target_path.is_file()
            or not _is_relative_to(target_path, target_dir)
        ):
            continue

        entry = os.path.relpath(target_path, target_dir)
        if _forward_slash():
            entry = entry.replace(os.sep, "/")
        entries.append(entry)

    return entries


def _read_playlist_entries(path: Path, relative_to: Path) -> list[Path]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (PermissionError, UnicodeDecodeError, OSError) as exc:
        raise UserError(f"could not read playlist {path}: {exc}") from exc

    entries = []
    for line in lines:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if "://" in line.strip():
            raise UserError(f"URL playlist entries are not supported: {line}")

        entry = Path(line).expanduser()
        entries.append(entry if entry.is_absolute() else relative_to / entry)
    return entries


def _playlist_files(directory: Path) -> list[Path]:
    return (
        sorted(
            path
            for path in directory.iterdir()
            if path.is_file() and path.suffix.lower() in PLAYLIST_SUFFIXES
        )
        if directory.exists()
        else []
    )


def _alternative_item_path(item: Item, collection: str) -> Path | None:
    path = item.get(f"alt.{collection}")
    return Path(os.fsdecode(path)) if path else None


def _items_by_path(lib: Library) -> dict[str, Item]:
    items = {}
    for item in lib.items():
        path = _normalized_path(Path(os.fsdecode(item.path)))
        if path in items:
            raise UserError(f"multiple library items use the same path: {item.path}")
        items[path] = item
    return items


def _alternative_directory(lib: Library, collection: str) -> Path:
    try:
        configured = Path(
            config["alternatives"][collection]["directory"].get(str)
        ).expanduser()
    except confuse.NotFoundError:
        configured = Path(collection)
    return configured if configured.is_absolute() else _library_dir(lib) / configured


def _playlist_dir(lib: Library) -> Path:
    try:
        value = config["playlist"]["playlist_dir"].get()
        if value:
            return Path(os.fsdecode(config["playlist"]["playlist_dir"].as_filename()))
    except (confuse.NotFoundError, OSError):
        pass
    return _library_dir(lib)


def _playlist_relative_to(lib: Library, playlist_path: Path) -> Path:
    try:
        value = config["playlist"]["relative_to"].get()
    except (confuse.NotFoundError, OSError):
        return _library_dir(lib)

    if not value or value == "library":
        return _library_dir(lib)
    if value == "playlist":
        return playlist_path.parent
    return Path(os.fsdecode(config["playlist"]["relative_to"].as_filename()))


def _forward_slash() -> bool:
    try:
        return config["playlist"]["forward_slash"].get(bool)
    except (confuse.NotFoundError, OSError):
        return False


def _library_dir(lib: Library) -> Path:
    return Path(os.fsdecode(lib.directory))


def _normalized_path(path: Path) -> str:
    normalized = os.path.realpath(os.path.expanduser(os.fspath(path)))
    return unicodedata.normalize("NFC", normalized).casefold()


def _name_key(name: str) -> str:
    return unicodedata.normalize("NFC", name).casefold()


def _is_relative_to(path: Path, directory: Path) -> bool:
    try:
        Path(os.path.abspath(path)).relative_to(Path(os.path.abspath(directory)))
    except ValueError:
        return False
    return True


def _same_directory(left: Path, right: Path) -> bool:
    if left.resolve() == right.resolve():
        return True
    if not right.exists():
        return False
    try:
        return os.path.samefile(left, right)
    except OSError:
        return False


def _generated_marker(collection: str) -> str:
    return f"# Generated by beet alternatives:{collection}"


def _remove_generated_playlist(path: Path, collection: str) -> None:
    if path.is_symlink() or not path.is_file():
        return
    try:
        first_line = path.read_text(encoding="utf-8").splitlines()[:1]
    except (PermissionError, UnicodeDecodeError, OSError):
        return
    if first_line in ([LEGACY_GENERATED_MARKER], [_generated_marker(collection)]):
        path.unlink()


def _require_marker_or_missing(path: Path, marker: str) -> None:
    if not path.exists() and not path.is_symlink():
        return
    if path.is_symlink() or not path.is_file():
        raise UserError(f"refusing to overwrite unowned playlist: {path}")

    try:
        first_line = path.read_text(encoding="utf-8").splitlines()[:1]
    except (PermissionError, UnicodeDecodeError, OSError) as exc:
        raise UserError(f"could not verify playlist ownership: {path}: {exc}") from exc
    if first_line not in ([LEGACY_GENERATED_MARKER], [marker]):
        raise UserError(f"refusing to overwrite unowned playlist: {path}")


def _atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, path)
    except BaseException:
        temporary_path.unlink(missing_ok=True)
        raise
