"""Playlist generation and ingestion from JSON."""

from __future__ import annotations

import json
import os
import tempfile
import unicodedata
from fractions import Fraction
from pathlib import Path
from typing import TYPE_CHECKING

import confuse
from beets import config
from beets.ui import Subcommand, UserError, should_write
from beets.util import sanitize_path

from . import fields

if TYPE_CHECKING:
    from beets.library import Item, Library
    from beets.plugins import BeetsPlugin

ORDER_STEP = 100
PLAYLIST_SUFFIXES: set[str] = {".m3u", ".m3u8"}
GENERATED_MARKER = "# Generated by beet jsonpl"
SMARTPLAYLIST_MARKER = "# Generated by beet smartplaylist"
SMARTPLAYLIST_MANIFEST = ".beets-wolframite-smartplaylists.json"
WINDOWS_RESERVED_NAMES = {
    "CON",
    "PRN",
    "AUX",
    "NUL",
    *(f"COM{index}" for index in range(1, 10)),
    *(f"LPT{index}" for index in range(1, 10)),
}


def atomic_write_text(path: Path, content: str) -> bool:
    """Atomically replace a text file, returning whether it changed."""
    path.parent.mkdir(parents=True, exist_ok=True)

    if not path.is_symlink():
        try:
            if path.read_text(encoding="utf-8") == content:
                return False
        except FileNotFoundError:
            pass
        except (IsADirectoryError, UnicodeDecodeError, OSError):
            pass

    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
    )
    temporary_path = Path(temporary_name)

    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())

        if path.exists() and not path.is_symlink():
            temporary_path.chmod(path.stat().st_mode)
        else:
            temporary_path.chmod(0o644)

        os.replace(temporary_path, path)
        return True
    except BaseException:
        temporary_path.unlink(missing_ok=True)
        raise


def commands(plugin: BeetsPlugin) -> list[Subcommand]:
    """Return beets CLI commands provided by this module."""
    command = Subcommand(
        "jsonpl",
        help="Manage JSON-backed playlists",
    )

    command.parser.add_option(
        "-w",
        "--write",
        action="store_true",
        dest="write",
        default=None,
        help="write changed playlist tags to files",
    )
    command.parser.add_option(
        "-W",
        "--nowrite",
        action="store_false",
        dest="write",
        help="do not write changed playlist tags to files",
    )
    command.parser.add_option(
        "--allow-empty",
        action="store_true",
        default=False,
        help="allow an empty playlist to remove every named membership",
    )

    command.func = lambda lib, opts, args: _dispatch(plugin, lib, opts, args)
    return [command]


def _dispatch(plugin: BeetsPlugin, lib: Library, opts, args: list[str]) -> None:
    if not args:
        raise UserError(
            "usage: beet jsonpl generate NAME... | generate-all | "
            "save PLAYLIST.m3u | sync-alternatives"
        )

    action = args[0]

    if action in {"generate", "gen"}:
        if len(args) < 2:
            raise UserError("usage: beet jsonpl generate NAME...")
        for path in generate_playlists(lib, args[1:]):
            plugin._log.info("Generated playlist {}", path)
        setattr(plugin, "_playlists_changed", True)

    elif action in {"generate-all", "gen-all"}:
        paths = generate_all_playlists(lib)
        for path in paths:
            plugin._log.info("Generated playlist {}", path)
        setattr(plugin, "_playlists_changed", True)

    elif action in {"sync-alternatives", "sync-alt"}:
        from . import alternatives

        alternatives.sync_all_collections(plugin, lib)

    elif action in {"save", "import"}:
        if len(args) != 2:
            raise UserError("usage: beet jsonpl save PLAYLIST.m3u")
        write = should_write(opts.write)
        changed = save_playlist(
            lib,
            Path(args[1]),
            write=write,
            allow_empty=opts.allow_empty,
        )
        generate_all_playlists(lib)
        setattr(plugin, "_playlists_changed", True)
        plugin._log.info("Saved playlist tags for {} item(s)", changed)

    else:
        raise UserError(f"unknown jsonpl action: {action}")


def generate_playlist(lib: Library, name: str) -> Path:
    """Generate m3u playlist by playlist name without suffix."""
    name = _normalize_playlist_name(name)
    playlists = _collect_playlists(lib)

    if name not in playlists:
        _remove_generated_playlist(_playlist_path(lib, name))
        raise UserError(f"playlist has no members: {name}")

    path = _playlist_path(lib, name)
    _write_m3u(lib, path, playlists[name])
    return path


def generate_playlists(lib: Library, names: list[str]) -> list[Path]:
    """Validate and generate multiple named playlists as one operation."""
    playlists = _collect_playlists(lib)
    normalized_names = [_normalize_playlist_name(name) for name in names]
    missing = [name for name in normalized_names if name not in playlists]
    if missing:
        raise UserError(f"playlist has no members: {', '.join(missing)}")

    paths = [_playlist_path(lib, name) for name in normalized_names]
    for path in paths:
        _require_marker_or_missing(path, GENERATED_MARKER)
    for name, path in zip(normalized_names, paths, strict=True):
        _write_m3u(lib, path, playlists[name])
    return paths


def generate_all_playlists(lib: Library) -> list[Path]:
    """Generate all valid playlists found in playlist memberships."""
    playlists = _collect_playlists(lib)
    paths = [_playlist_path(lib, name) for name in sorted(playlists)]

    for path in paths:
        _require_marker_or_missing(path, GENERATED_MARKER)

    for name, path in zip(sorted(playlists), paths, strict=True):
        _write_m3u(lib, path, playlists[name])

    _remove_stale_generated_playlists(lib, set(paths))

    return paths


def reconcile_smartplaylists(
    plugin,
    lib: Library,
    definitions: set,
    full_update: bool,
) -> None:
    """Clear empty outputs and remove stale smart-playlist files."""
    if plugin.config["pretend"].get(bool):
        return

    output = plugin.config["output"].get()
    directory = Path(os.fsdecode(plugin.config["playlist_dir"].as_filename()))
    outputs, outputs_by_definition = _smartplaylist_output_plan(
        plugin,
        lib,
        definitions,
        directory,
    )

    for path, has_entries in outputs.items():
        if not has_entries:
            content = (
                f"#EXTM3U\n{SMARTPLAYLIST_MARKER}\n"
                if output == "extm3u"
                else f"{SMARTPLAYLIST_MARKER}\n"
            )
            atomic_write_text(path, content)
        else:
            _mark_smartplaylist(path)

    manifest = directory / SMARTPLAYLIST_MANIFEST
    previous = _read_smartplaylist_manifest(manifest)
    current = {
        name: {
            relative
            for path in paths
            if (relative := _relative_manifest_path(path, directory)) is not None
        }
        for name, paths in outputs_by_definition.items()
    }

    if full_update:
        updated = current
        stale_names = {
            path for paths in previous.values() for path in paths
        } - {path for paths in updated.values() for path in paths}
    else:
        updated = {**previous, **current}
        stale_names = {
            path
            for name in current
            for path in previous.get(name, set()) - current[name]
        }

    retained_names = {path for paths in updated.values() for path in paths}
    for name in stale_names - retained_names:
        stale = _safe_manifest_target(directory, name)
        if stale is not None and _has_marker(stale, SMARTPLAYLIST_MARKER):
            stale.unlink()

    atomic_write_text(
        manifest,
        json.dumps(
            {name: sorted(paths) for name, paths in sorted(updated.items())},
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
    )


def validate_smartplaylist_outputs(plugin, lib: Library, definitions: set) -> None:
    """Refuse to let smartplaylist replace files it does not own."""
    if plugin.config["pretend"].get(bool):
        return

    directory = Path(os.fsdecode(plugin.config["playlist_dir"].as_filename()))
    outputs, _by_definition = _smartplaylist_output_plan(
        plugin,
        lib,
        definitions,
        directory,
    )
    for path in outputs:
        relative = _relative_manifest_path(path, directory)
        if relative is None:
            raise UserError(f"smartplaylist output escapes its directory: {path}")
        if not path.exists() and not path.is_symlink():
            continue
        if _has_marker(path, SMARTPLAYLIST_MARKER):
            continue
        raise UserError(f"refusing to overwrite unowned smartplaylist: {path}")


def _smartplaylist_output_plan(
    plugin,
    lib: Library,
    definitions: set,
    directory: Path,
) -> tuple[dict[Path, bool], dict[str, set[Path]]]:
    outputs: dict[Path, bool] = {}
    outputs_by_definition: dict[str, set[Path]] = {}

    for name, item_query, album_query in definitions:
        decoded_name = os.fsdecode(name)
        items = list(plugin.get_playlist_items(lib, item_query, album_query))
        definition_outputs = outputs_by_definition.setdefault(decoded_name, set())

        for item in items:
            filename = item.evaluate_template(name, True)
            filename = sanitize_path(filename, lib.replacements)
            path = directory / filename
            outputs[path] = True
            definition_outputs.add(path)

        if not items and "$" not in decoded_name and "%" not in decoded_name:
            filename = sanitize_path(decoded_name, lib.replacements)
            path = directory / filename
            outputs.setdefault(path, False)
            definition_outputs.add(path)
    return outputs, outputs_by_definition


def _read_smartplaylist_manifest(path: Path) -> dict[str, set[str]]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (FileNotFoundError, PermissionError, UnicodeDecodeError, json.JSONDecodeError):
        return {}

    if isinstance(value, list):
        return {
            "__legacy__": {name for name in value if isinstance(name, str)},
        }
    if not isinstance(value, dict):
        return {}

    return {
        str(name): {path for path in paths if isinstance(path, str)}
        for name, paths in value.items()
        if isinstance(paths, list)
    }


def _relative_manifest_path(path: Path, directory: Path) -> str | None:
    try:
        return path.relative_to(directory).as_posix()
    except ValueError:
        return None


def _safe_manifest_target(directory: Path, name: str) -> Path | None:
    relative = Path(name)
    if relative.is_absolute() or ".." in relative.parts:
        return None
    target = directory / relative
    try:
        target.resolve(strict=False).relative_to(directory.resolve(strict=False))
    except ValueError:
        return None
    return target


def save_playlist(
    lib: Library,
    playlist_path: Path,
    write: bool,
    allow_empty: bool = False,
) -> int:
    """Ingest an m3u playlist into item playlist_memberships.

    The playlist name is derived from the m3u filename. Existing membership for
    that playlist is overwritten across the library.
    """
    playlist_path = playlist_path.expanduser()
    name = _playlist_name_from_path(playlist_path)
    relative_to = _relative_to(lib, playlist_path)

    paths = _read_m3u(playlist_path, relative_to)
    if not paths and not allow_empty:
        raise UserError(
            "playlist contains no file entries; use --allow-empty to clear it"
        )

    library_items = list(lib.items())
    item_by_path = _items_by_path(lib, library_items)
    source_memberships = {
        _item_id(item): _file_memberships(item) if write else _memberships(item)
        for item in library_items
    }

    ordered_items = []
    missing_paths = []
    seen_ids = set()

    for path in paths:
        item = item_by_path.get(_normalized_path(path))
        if item is None:
            missing_paths.append(path)
            continue

        if item.id in seen_ids:
            raise UserError(f"playlist contains an item more than once: {path}")

        seen_ids.add(item.id)
        ordered_items.append(item)

    if missing_paths:
        missing = "\n".join(f"  {path}" for path in missing_paths)
        raise UserError(f"playlist contains paths not in beets library:\n{missing}")

    desired_order = _desired_playlist_order(
        ordered_items,
        name,
        source_memberships,
    )

    changed_items = []

    for item in library_items:
        item_id = _item_id(item)
        memberships = dict(source_memberships[item_id])
        database_memberships = _memberships(item)
        file_memberships = dict(memberships)

        for existing_name in list(memberships):
            if _same_playlist_name(existing_name, name):
                del memberships[existing_name]

        if item_id in desired_order:
            memberships[name] = desired_order[item_id]

        needs_store = memberships != database_memberships
        needs_write = write and memberships != file_memberships
        if needs_store or needs_write:
            _set_memberships(item, memberships)
            changed_items.append(item)

    _sync_changed_items(lib, changed_items, write)
    canonical_path = _playlist_path(lib, name)
    if _normalized_path(playlist_path) == _normalized_path(canonical_path):
        _claim_generated_playlist(canonical_path)
    return len(changed_items)


def _collect_playlists(
    lib: Library,
) -> dict[str, list[tuple[fields.PlaylistOrder, Item]]]:
    playlists: dict[str, list[tuple[fields.PlaylistOrder, Item]]] = {}
    source_names: dict[str, str] = {}

    for item in lib.items():
        for name, order in _file_memberships(item).items():
            if not _is_valid_playlist_name(name):
                continue

            normalized = _normalize_playlist_name(name)
            key = _name_key(normalized)
            previous = source_names.get(key)
            if previous is not None and previous != name:
                raise UserError(
                    f"playlist names resolve to the same output file: "
                    f"{previous}, {name}"
                )

            source_names[key] = name
            playlists.setdefault(normalized, []).append((order, item))

    for entries in playlists.values():
        entries.sort(key=lambda entry: (entry[0], *_item_sort_key(entry[1])))

    return playlists


def _write_m3u(
    lib: Library,
    path: Path,
    entries: list[tuple[fields.PlaylistOrder, Item]],
) -> None:
    relative_to = _relative_to(lib, path)
    forward_slash = _forward_slash()

    lines = []
    for _, item in entries:
        item_path = _path_from_beets(item.path)
        playlist_entry = os.path.relpath(item_path, relative_to)
        if "\n" in playlist_entry or "\r" in playlist_entry:
            raise UserError(f"playlist path contains a newline: {item_path}")
        if forward_slash:
            playlist_entry = playlist_entry.replace(os.sep, "/")
        lines.append(playlist_entry)

    _require_marker_or_missing(path, GENERATED_MARKER)
    atomic_write_text(
        path,
        "\n".join([GENERATED_MARKER, *lines]) + "\n",
    )


def _read_m3u(path: Path, relative_to: Path) -> list[Path]:
    if path.suffix.lower() not in PLAYLIST_SUFFIXES:
        raise UserError(f"playlist path must end with .m3u or .m3u8: {path}")

    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        raise UserError(f"playlist file does not exist: {path}") from None
    except IsADirectoryError:
        raise UserError(f"playlist path is a directory: {path}") from None
    except PermissionError:
        raise UserError(f"playlist file is not readable: {path}") from None
    except UnicodeDecodeError as exc:
        raise UserError(f"playlist file is not valid UTF-8: {path}: {exc}") from None
    except OSError as exc:
        raise UserError(f"could not read playlist file {path}: {exc}") from None

    entries = []

    for raw_line in lines:
        line = raw_line
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if "://" in line.strip():
            raise UserError(f"URL playlist entries are not supported: {line}")

        entry = Path(line).expanduser()
        if not entry.is_absolute():
            entry = relative_to / entry

        entries.append(entry)

    return entries


def _memberships(item: Item) -> dict[str, fields.PlaylistOrder]:
    try:
        return fields.loads_playlist_memberships(item.get("playlist_memberships"))
    except Exception as exc:
        raise UserError(f"invalid playlist_memberships on item {item.id}: {exc}")


def _file_memberships(item: Item) -> dict[str, fields.PlaylistOrder]:
    try:
        return fields.loads_playlist_memberships(
            fields.read_item_field(item, "playlist_memberships")
        )
    except Exception as exc:
        raise UserError(
            f"invalid file playlist_memberships on item {item.id}: {exc}"
        ) from exc


def _set_memberships(
    item: Item,
    memberships: dict[str, fields.PlaylistOrder],
) -> None:
    item["playlist_memberships"] = (
        fields.dumps_playlist_memberships(memberships) if memberships else ""
    )


def _sync_changed_items(lib: Library, items: list[Item], write: bool) -> None:
    seen = set()
    unique_items = []

    for item in items:
        if item.id in seen:
            continue
        seen.add(item.id)
        unique_items.append(item)

    if not write:
        with fields.atomic(lib):
            for item in unique_items:
                item.store()
        return

    fields.write_item_fields_batch(
        [(item, {"playlist_memberships"}) for item in unique_items]
    )
    with fields.atomic(lib):
        for item in unique_items:
            item.store()


def _items_by_path(
    lib: Library,
    library_items: list[Item] | None = None,
) -> dict[str, Item]:
    items = {}
    for item in library_items if library_items is not None else lib.items():
        path = _normalized_path(_path_from_beets(item.path))
        if path in items:
            raise UserError(f"multiple library items use the same path: {item.filepath}")
        items[path] = item
    return items


def _desired_playlist_order(
    ordered_items: list[Item],
    name: str,
    memberships_by_id: dict[int, dict[str, fields.PlaylistOrder]],
) -> dict[int, fields.PlaylistOrder]:
    existing = {
        _item_id(item): order
        for item in ordered_items
        if (
            order := _membership_order(memberships_by_id[_item_id(item)], name)
        )
        is not None
    }
    item_by_id = {_item_id(item): item for item in ordered_items}
    desired_existing = [
        item_id
        for item in ordered_items
        if (item_id := _item_id(item)) in existing
    ]
    current_existing = sorted(
        desired_existing,
        key=lambda item_id: (existing[item_id], _item_sort_key(item_by_id[item_id])),
    )

    if desired_existing != current_existing:
        return {
            _item_id(item): index * ORDER_STEP
            for index, item in enumerate(ordered_items, start=1)
        }

    desired = {item_id: order for item_id, order in existing.items()}
    positions = [existing.get(_item_id(item)) for item in ordered_items]
    index = 0
    while index < len(ordered_items):
        if positions[index] is not None:
            index += 1
            continue

        start = index
        while index < len(ordered_items) and positions[index] is None:
            index += 1
        end = index
        previous = positions[start - 1] if start else None
        following = positions[end] if end < len(positions) else None
        inserted = end - start
        allocated = _allocate_orders(previous, following, inserted)

        for item, order in zip(ordered_items[start:end], allocated, strict=True):
            desired[_item_id(item)] = order

    return desired


def _membership_order(
    memberships: dict[str, fields.PlaylistOrder],
    name: str,
) -> fields.PlaylistOrder | None:
    orders = [
        order
        for existing_name, order in memberships.items()
        if _same_playlist_name(existing_name, name)
    ]
    if len(orders) > 1:
        raise UserError(f"item has duplicate aliases for playlist: {name}")
    return orders[0] if orders else None


def _allocate_orders(
    previous: fields.PlaylistOrder | None,
    following: fields.PlaylistOrder | None,
    count: int,
) -> list[fields.PlaylistOrder]:
    if previous is None and following is None:
        return [index * ORDER_STEP for index in range(1, count + 1)]
    if previous is None:
        assert following is not None
        return [following - ORDER_STEP * index for index in range(count, 0, -1)]
    if following is None:
        return [previous + ORDER_STEP * index for index in range(1, count + 1)]

    gap = following - previous
    return [
        Fraction(previous) + Fraction(gap * index, count + 1)
        for index in range(1, count + 1)
    ]


def _item_id(item: Item) -> int:
    if item.id is None:
        raise UserError(f"playlist item has no database id: {item.path}")
    return item.id


def _playlist_path(lib: Library, name: str) -> Path:
    return _playlist_dir(lib) / f"{_normalize_playlist_name(name)}.m3u"


def _playlist_name_from_path(path: Path) -> str:
    if path.suffix.lower() not in PLAYLIST_SUFFIXES:
        raise UserError(f"playlist path must end with .m3u or .m3u8: {path}")

    return _normalize_playlist_name(path.stem)


def _normalize_playlist_name(name: str) -> str:
    name = unicodedata.normalize("NFC", name)
    changed = True
    while changed:
        changed = False
        for suffix in (".m3u8", ".m3u"):
            if name.lower().endswith(suffix):
                name = name[: -len(suffix)]
                changed = True
                break

    if not _is_valid_playlist_name(name):
        raise UserError(f"invalid playlist name: {name}")

    return name


def _is_valid_playlist_name(name: str) -> bool:
    if (
        not name
        or name != name.strip()
        or name in {".", ".."}
        or "\0" in name
        or name.endswith(".")
        or any(character in name for character in '<>:"/\\|?*')
        or name.split(".", 1)[0].upper() in WINDOWS_RESERVED_NAMES
    ):
        return False

    return True


def _same_playlist_name(left: str, right: str) -> bool:
    return (
        _is_valid_playlist_name(left)
        and _name_key(_normalize_playlist_name(left))
        == _name_key(_normalize_playlist_name(right))
    )


def _playlist_dir(lib: Library) -> Path:
    configured = [
        path
        for section in ("smartplaylist", "playlist")
        if (path := _config_filename(section, "playlist_dir")) is not None
    ]
    return _consistent_path(configured, "playlist_dir") or _path_from_beets(
        lib.directory
    )


def _relative_to(lib: Library, playlist_path: Path) -> Path:
    configured = [
        path
        for section in ("smartplaylist", "playlist")
        if (
            path := _config_relative_to(
                section,
                "relative_to",
                lib,
                playlist_path,
            )
        )
        is not None
    ]
    return _consistent_path(configured, "relative_to") or _path_from_beets(
        lib.directory
    )


def _forward_slash() -> bool:
    configured = [
        value
        for section in ("smartplaylist", "playlist")
        if (value := _config_bool(section, "forward_slash")) is not None
    ]
    if len(set(configured)) > 1:
        raise UserError("conflicting playlist forward_slash settings")
    return configured[0] if configured else False


def _config_filename(section: str, key: str) -> Path | None:
    if not _has_explicit_setting(section, key):
        return None

    try:
        value = config[section][key].get()
    except (confuse.NotFoundError, OSError):
        return None

    if not value:
        return None

    return Path(os.fsdecode(config[section][key].as_filename()))


def _config_relative_to(
    section: str,
    key: str,
    lib: Library,
    playlist_path: Path,
) -> Path | None:
    if not _has_explicit_setting(section, key):
        return None

    try:
        value = config[section][key].get()
    except (confuse.NotFoundError, OSError):
        return None

    if not value:
        return None

    if value == "library":
        return _path_from_beets(lib.directory)

    if value == "playlist":
        return playlist_path.parent

    return Path(os.fsdecode(config[section][key].as_filename()))


def _config_bool(section: str, key: str) -> bool | None:
    if not _has_explicit_setting(section, key):
        return None

    try:
        return config[section][key].get(bool)
    except (confuse.NotFoundError, OSError):
        return None


def _has_explicit_setting(section: str, key: str) -> bool:
    try:
        return any(
            not source.default for _value, source in config[section][key].resolve()
        )
    except (confuse.NotFoundError, OSError):
        return False


def _consistent_path(paths: list[Path], setting: str) -> Path | None:
    if not paths:
        return None

    normalized = {os.path.normpath(os.fspath(path)) for path in paths}
    if len(normalized) > 1:
        raise UserError(f"conflicting playlist {setting} settings")
    return paths[0]


def _path_from_beets(path) -> Path:
    return Path(os.fsdecode(path))


def _normalized_path(path: Path) -> str:
    normalized = os.path.realpath(os.path.expanduser(os.fspath(path)))
    return unicodedata.normalize("NFC", normalized).casefold()


def _remove_generated_playlist(path: Path) -> None:
    if _has_marker(path, GENERATED_MARKER):
        path.unlink()


def _require_marker_or_missing(path: Path, marker: str) -> None:
    if not path.exists() and not path.is_symlink():
        return
    if path.is_symlink() or not _has_marker(path, marker):
        raise UserError(f"refusing to overwrite unowned playlist: {path}")


def _has_marker(path: Path, marker: str) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    try:
        return marker in path.read_text(encoding="utf-8").splitlines()[:2]
    except (PermissionError, UnicodeDecodeError, OSError):
        return False


def _mark_smartplaylist(path: Path) -> None:
    if not path.is_file() or path.is_symlink():
        raise UserError(f"smartplaylist output is not a regular file: {path}")

    content = path.read_text(encoding="utf-8")
    lines = content.splitlines(keepends=True)
    if SMARTPLAYLIST_MARKER in (line.rstrip("\r\n") for line in lines[:2]):
        return

    index = 1 if lines and lines[0].rstrip("\r\n") == "#EXTM3U" else 0
    lines.insert(index, f"{SMARTPLAYLIST_MARKER}\n")
    atomic_write_text(path, "".join(lines))


def _claim_generated_playlist(path: Path) -> None:
    """Mark an explicitly saved canonical playlist as plugin-owned."""
    if _has_marker(path, GENERATED_MARKER):
        return
    if path.is_symlink() or not path.is_file():
        raise UserError(f"canonical playlist is not a regular file: {path}")

    content = path.read_text(encoding="utf-8")
    lines = content.splitlines(keepends=True)
    index = 1 if lines and lines[0].rstrip("\r\n") == "#EXTM3U" else 0
    lines.insert(index, f"{GENERATED_MARKER}\n")
    atomic_write_text(path, "".join(lines))


def _remove_stale_generated_playlists(lib: Library, expected: set[Path]) -> None:
    directory = _playlist_dir(lib)
    if not directory.exists():
        return

    expected_names = {_name_key(path.name) for path in expected}
    for path in directory.iterdir():
        if (
            path.suffix.lower() in PLAYLIST_SUFFIXES
            and _name_key(path.name) not in expected_names
        ):
            _remove_generated_playlist(path)


def _name_key(name: str) -> str:
    return unicodedata.normalize("NFC", name).casefold()


def _item_sort_key(item: Item) -> tuple[str, str, int, int, str, str]:
    return (
        unicodedata.normalize("NFC", str(item.get("albumartist", ""))).casefold(),
        unicodedata.normalize("NFC", str(item.get("album", ""))).casefold(),
        int(item.get("disc", 0) or 0),
        int(item.get("track", 0) or 0),
        unicodedata.normalize("NFC", str(item.get("title", ""))).casefold(),
        _normalized_path(_path_from_beets(item.path)),
    )
