-- Grammar checker

local M = {
  "harper_ls",
  for_cat = "formatting",
  lsp = {
    filetypes = {
      "asciidoc",
      "c",
      "clojure",
      "cmake",
      "cpp",
      "cs",
      "dart",
      "gitcommit",
      "go",
      "groovy",
      "haskell",
      "html",
      "java",
      "javascript",
      "javascriptreact",
      "jjdescription",
      "kotlin",
      "lhaskell",
      "lua",
      "mail",
      "markdown",
      "nix",
      "org",
      "php",
      "python",
      "ruby",
      "rust",
      "scala",
      "sh",
      "solidity",
      "swift",
      "text",
      "toml",
      "typescript",
      "typescriptreact",
      "typst",
      "zig",
      "tex",
      "plaintex",
    },
    settings = {
      ["harper-ls"] = {},
    },
  },
}

return M
